version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      
  test:
      docker:
        - image: circleci/node:11.10.1
      steps:
        - checkout
        - run: yarn install
        - run: yarn test:unit

workflows:
  version: 2
  integration:
    jobs:
      - build
      - test






      
