 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/advertisements", type: :request do
  
  # Advertisement. As you add validations to Advertisement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Advertisement.create! valid_attributes
      get advertisements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      advertisement = Advertisement.create! valid_attributes
      get advertisement_url(advertisement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      Advertisement.create! valid_attributes
      get new_advertisement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      advertisement = Advertisement.create! valid_attributes
      get edit_advertisement_url(advertisement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Advertisement" do
        expect {
          post advertisements_url, params: { advertisement: valid_attributes }
        }.to change(Advertisement, :count).by(1)
      end

      it "redirects to the created advertisement" do
        post advertisements_url, params: { advertisement: valid_attributes }
        expect(response).to redirect_to(advertisement_url(Advertisement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Advertisement" do
        expect {
          post advertisements_url, params: { advertisement: invalid_attributes }
        }.to change(Advertisement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post advertisements_url, params: { advertisement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested advertisement" do
        advertisement = Advertisement.create! valid_attributes
        patch advertisement_url(advertisement), params: { advertisement: new_attributes }
        advertisement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the advertisement" do
        advertisement = Advertisement.create! valid_attributes
        patch advertisement_url(advertisement), params: { advertisement: new_attributes }
        advertisement.reload
        expect(response).to redirect_to(advertisement_url(advertisement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        advertisement = Advertisement.create! valid_attributes
        patch advertisement_url(advertisement), params: { advertisement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested advertisement" do
      advertisement = Advertisement.create! valid_attributes
      expect {
        delete advertisement_url(advertisement)
      }.to change(Advertisement, :count).by(-1)
    end

    it "redirects to the advertisements list" do
      advertisement = Advertisement.create! valid_attributes
      delete advertisement_url(advertisement)
      expect(response).to redirect_to(advertisements_url)
    end
  end
end
