default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

test:
  <<: *default
  database: hipsters_test

staging:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  