development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_dev
  socket: /var/run/mysqld/mysqld.sock
  username: <%= ENV["DEV_USER"] %>
  password: <%= ENV["DEV_PASSWORD"] %>
  
staging:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  host: <%= ENV["STAGING_HOST"] %>
  username: <%= ENV["STAGING_USER"] %>
  password: <%= ENV["STAGING_PASSWORD"] %>

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_test
  socket: /var/run/mysqld/mysqld.sock
  username: <%= ENV["TEST_USER"] %>
  password: <%= ENV["TEST_PASSWORD"] %>