development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_dev
  socket: /var/run/mysqld/mysqld.sock
  username: kirua
  password: kirua
  
test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_test
  socket: /var/run/mysqld/mysqld.sock
  username: kirua
  password: kirua
  